project:
  type: website
  resources:
    - cv-092025.pdf
    - favicon.svg
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "!posts_raw/"

website:
  title: "Axel Verrier"
  search: false
  favicon: favicon.svg
  back-to-top-navigation: true
  page-footer: "Axel Verrier · Content licensed under CC BY 4.0"
  navbar:
    right:
      - text: Papers
        href: papers.qmd
      - text: Blog
        href: blog.html
      - text: Side quests
        menu:
          - text: Programme des théâtres parisiens
            href: https://axelverrier.github.io/programmedestheatres/
      # - text: Teaching
      #   href: teaching.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
