---
title: "Research"
---

## Working papers

**Quantifying digital innovation for the twin transition: Historical trends, current landscape and links with environmental innovation**
Aklilu, A., D. Dussaux and A. Verrier (2025)
*OECD Environment Working Papers, No. 261, OECD Publishing, Paris*
[DOI: 10.1787/8cc4cff0-en](https://doi.org/10.1787/8cc4cff0-en)

<details>
<summary>Abstract</summary>

The digital transformation offers environmental opportunities as well as great environmental challenges. To maximise synergies and minimise trade-offs in the parallel ongoing digital and environmental transition, also known as the “twin” transition, policy makers need reliable indicators to measure and monitor thedigital and green transformation. This working paper develops new patent-based indicators to measure digital innovation more comprehensively as well as “twin transition” innovation that is both digital and environmental. The paper provides recent global trends in digital and twin transition innovation and investigates the role of previous digital innovation for environmental innovation. Despite representing a small fraction of total patenting twin transition patenting grew by an impressive 9.7% per year on average between 2005 and 2020. Twin transition patenting is heavily focused on climate change mitigation and is more concentrated geographically than total patenting. Finally, digital innovation can have a positive influence on environmental innovation as at least a third of patented environmental inventions cite digital inventions.

</details>

---

## Work in progress

*Coming soon.*
